### ISSUE TITLE
User supplied word list

### ISSUE THREAD

**Issue by ppetru** [ppetru/morse-camp#7]
Allow users to supply a word list that would replace the built in dictionary.

Since the app is completely client side right now, this would likely take the form of a textarea that the user can paste the list into (one word per line or similar), then save the contents to local storage and use it when selected by the user through a config toggle.

**Comment by ppetru** [comment]
@zoglmannk I just committed the implementation of this to the master branch. It *seems* to work, but please let me know if you notice anything funky. I'll hold off pushing it to production for now.

**Comment by zoglmannk** [comment]
Awesome. I will check it out! I am interested to see what you ended up doing with this request. I was considering implementing this one too. :)

**Comment by zoglmannk** [comment]
I am looking at it this morning...

**Comment by zoglmannk** [comment]
On first glance, the implementation looks and works great!

As a tester, I tried to break your implementation. There are a few small things that would improve the implementation.  

1) If in addition to "normalizing and deduplicating" the dictionary, it would be helpful to extend the filtering to remove multiple unexpected characters that might come in from cut-and-pasting an article into the text field. If you input "<<AS<<<" it gets filtered to "<AS<<<". The unexpected characters do not break the Read Trainer, so that's good! The erroneous characters are ignored.

2) If you cut and paste an article that has long very long lines, the text area is not constrained and messes up the formatting of the whole page. It can difficult to find the SAVE button. If you go to this URL ( http://avalon.law.yale.edu/18th_century/artconf.asp ) and cut-and-paste Section IX, you can reproduce the issue.

3) With a huge custom dictionary, it takes a lot of scrolling to reach the SAVE button.

4) It would be even more awesome if in the analysis phase the implementation counted the word occurrences, stored the frequency hidden away, and sorted the visible list by frequency.

Thank you for all your hard work on this! I can also provide some assistance if you want help with this feature. Or it might be okay to release it now and improve it iteratively.

**Comment by ppetru** [comment]
Wow, you're good at this! :D Thanks for the thorough testing.

I fixed the first issue and mostly fixed the 2nd and 3rd (it has some smaller arbitrary bounds now). The last one is intriguing but I'm punting on it for now because I'm lazy :) (but you did remind me that it used to sort the words and that broke midway, so fixed that as well).

I'll release it as is -- welcoming any further tweaks / improvements if you want to take on them.

**Comment by zoglmannk** [comment]
Thanks. In our office, we have fantastic QA person, Cindy. Her attention to detail during testing is impeccable. Perhaps I made her a little proud? hehe

I won't be able to make many contributions until after Thanksgiving. I have a lot of traveling over the break. I look forward to helping out further. I have enjoyed using Morse Camp and hacking away on it. This is the first time I have ever taken a look at React. Our tech stack is a little more dated at work.

Recently I started to practice at 48wpm and having some success.
